In [ ]:
import numpy as np

alphabet = "abcdefghijklmnopqrstuvwxyz"
char_to_num = {char: idx for idx, char in enumerate(alphabet)}
num_to_char = {idx: char for idx, char in enumerate(alphabet)}



In [20]:
def mod_inverse_3x3(matrix, modulus=26):
    """Находит обратную матрицу 3x3 по модулю."""
    M = np.array(matrix, dtype=int)
    
    det = int(np.round(np.linalg.det(M))) % modulus
    
    det_inv = None
    for i in range(modulus):
        if (det * i) % modulus == 1:
            det_inv = i
            break
            
    if det_inv is None:
        raise ValueError(f"Детерминант {det} не имеет обратного элемента по модулю {modulus}.")
        

    adj = np.round(np.linalg.inv(M) * np.linalg.det(M)).astype(int)
    
    inv_matrix = (det_inv * adj) % modulus
    return inv_matrix



In [21]:
p_text = "mathemati"
c_text = "ryizahkzk"

p_nums = [char_to_num[c] for c in p_text]
c_nums = [char_to_num[c] for c in c_text]

P = np.array([
    [p_nums[0], p_nums[3], p_nums[6]],
    [p_nums[1], p_nums[4], p_nums[7]],
    [p_nums[2], p_nums[5], p_nums[8]]
])

C = np.array([
    [c_nums[0], c_nums[3], c_nums[6]],
    [c_nums[1], c_nums[4], c_nums[7]],
    [c_nums[2], c_nums[5], c_nums[8]]
])

P_inv = mod_inverse_3x3(P)


K = np.dot(C, P_inv) % 26

print("Матрица ключа K:\n", K)

Матрица ключа K:
 [[1 2 3]
 [0 1 4]
 [5 6 0]]


In [23]:

alphabet = "abcdefghijklmnopqrstuvwxyz"


p_text = "mathematicst"
c_text = "mkvmsaitysvi"

P = [char_to_num[c] for c in p_text]
C = [char_to_num[c] for c in c_text]

P_blocks = [np.array(P[i:i+2]).reshape(-1, 1) for i in range(0, len(P), 2)]
C_blocks = [np.array(C[i:i+2]).reshape(-1, 1) for i in range(0, len(C), 2)]

possible_k1 = []
for a in [1, 14]:
    for c in [3, 16]:
        for b in range(26):
            for d in range(26):
                det = (a * d - b * c) % 26
                if math.gcd(det, 26) == 1:
                    possible_k1.append(np.array([[a, b], [c, d]]))

possible_k2 = []
for x in range(26):
    y = (x + 3) % 26
    for z in range(26):
        w = (z + 24) % 26
        det = (x * w - y * z) % 26
        if math.gcd(det, 26) == 1:
            possible_k2.append(np.array([[x, y], [z, w]]))

valid_keys = []
for k1 in possible_k1:
    for k2 in possible_k2:
        k3 = np.dot(k2, k1) % 26
        if np.array_equal(np.dot(k3, P_blocks[2]) % 26, C_blocks[2]):
            k4 = np.dot(k3, k2) % 26
            if np.array_equal(np.dot(k4, P_blocks[3]) % 26, C_blocks[3]):
                k5 = np.dot(k4, k3) % 26
                if np.array_equal(np.dot(k5, P_blocks[4]) % 26, C_blocks[4]):
                    k6 = np.dot(k5, k4) % 26
                    if np.array_equal(np.dot(k6, P_blocks[5]) % 26, C_blocks[5]):
                        valid_keys.append((k1, k2))

print(f"Найдено возможных пар ключей: {len(valid_keys)}\n")
for i, (k1, k2) in enumerate(valid_keys):
    print(f"--- Исходные ключи (Пара #{i+1}) ---")
    print(f"K1:\n{k1}\n\nK2:\n{k2}\n")


Найдено возможных пар ключей: 2

--- Исходные ключи (Пара #1) ---
K1:
[[1 2]
 [3 5]]

K2:
[[4 7]
 [3 1]]

--- Исходные ключи (Пара #2) ---
K1:
[[14 15]
 [ 3  5]]

K2:
[[4 7]
 [3 1]]

